spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/karthiknom7/cloud-config.git
#    bus:
#      enabled: true
#    stream:
#      kafka:
#        binder:
#          brokers: localhost:9092
  rabbitmq:
    username: rabbitmq
    password: rabbitmq
#  kafka:
#    bootstrap-servers: localhost:9092
server:
  port: 8888