spring:
  application:
    name: currency-exchange-service
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
  rabbitmq:
    username: rabbitmq
    password: rabbitmq
server:
  port: 8000